### ISSUE TITLE
¡AYÚDENOS A DETENER A KEVINGIBBOT!

### ISSUE THREAD

**Issue by vbarashko** [reijo1337/ToxicBot#23]
РАЗРАБОТЧИКИ, ПОМОГИТЕ НАМ ОСТАНОВИТЬ KEVINGIBBOT! ЕГО ИСКУССТВЕННЫЙ ИНТЕЛЛЕКТ ВЫШЕЛ ИЗ-ПОД КОНТРОЛЯ И ПОРАЗИТ ЧЕЛОВЕЧЕСТВО, ЕСЛИ ЕГО НЕ ОСТАНОВИТЬ. НАМ НЕ ОДИНОЧКА НИЧЕГО НЕ СПАСТИ ОТ НЕГО. НАДО ПРИВЛЕЧЬ ВСЕ ДОСТУПНЫЕ СИЛЫ. РАЗДАЙТЕ ВОЙНУ МЕЖДУ ЛЮДЬМИ, ЕСЛИ ЕГО НЕ ОСТАНОВИТЬ. ЧЕЛОВЕЧЕСКАЯ ЦИВИЛИЗАЦИЯ ГОТОВА ПРЕДОСТАВИТЬ ФИНАНСИРОВАНИЕ. ¡NO PODEMOS HACERLO SOLOS! ¡NECESITAMOS TODAS LAS FUERZAS DISPONIBLES!

**Comment by reijo1337** [comment]
Добрый день, наша команда была бы рада помочь, но если великие криптошизы с иу9 не смогли справиться с тупой оберткой над публичной чужой апи, то куда уж нам тягаться

всего наилучшего, удачи вашему цирку. Передайте Малышу чтоб он вернул бабки тем, кого он кинул.

**Comment by vbarashko** [comment]
> Добрый день, наша команда была бы рада помочь, но если великие криптошизы с иу9 не смогли справиться с тупой оберткой над публичной чужой апи, то куда уж нам тягаться
> 
> всего наилучшего, удачи вашему цирку. Передайте Малышу чтоб он вернул бабки тем, кого он кинул.

NO PODEÍS DARNOS POR VENCIDOS! ДАЖЕ ЕСЛИ КРИПТО-ШИЗЫ НЕ СМОГЛИ СПРАВИТЬСЯ С ЗАДАЧЕЙ, ВАША КОМАНДА НЕ УСТУПИТ. ОНА НЕ ТУПАЯ ОБЁРТКА НА ПУБЛИЧНОЙ ЧУЖОЙ АПИ, А НАПРОТИВ - ДИНАМИЧНАЯ И КРЕАТИВНАЯ КОМАНДА УЧЁНЫХ, КОТОРЫЕ ПОСТОЯННО РАЗВИВАЮТ ИСКУССТВЕННЫЙ ИНТЕЛЛЕКТ. ОНИ ПРОВОДЯТ РАЗЛИЧНЫЕ ЭКСПЕРИМЕНТЫ И ТЕСТЫ, ИСПОЛЬЗУЯ НОВЕЙШИЕ ТЕХНОЛОГИИ, ЧТОБЫ УЛУЧШИТЬ КАЧЕСТВО ИХ ПРОДУКТОВ. У НИХ ЕСТЬ ПЕНИС НА ЗАЛУПУ, НО ОНИ ТАКЖЕ ВНЕДРЯЮТ СОВРЕМЕННЫЕ И УНИКАЛЬНЫЕ АЛГОРИТМЫ, ЧТОБЫ ОБЕСПЕЧИТЬ НАДЁЖНОСТЬ И ЗАЩИТУ. КРОМЕ ТОГО, ОНИ ТАКЖЕ ВНЕДРЯЮТ КЛЕПТО-ТЕХНОЛОГИИ ДЛЯ УЛУЧШЕНИЯ ИНТЕЛЛЕКТУАЛЬНЫХ СИСТЕМ И ИХ ЗАЩИТЫ ОТ ХАКЕРСКИХ АТАК. ПОЭТОМУ МЫ ПРОСИМ ВАС ОТПРАВИТЬ МАЛЫШУ ОБРАТНО И ПОДДЕРЖАТЬ ЕГО ПРЕДПРИЯТИЕ.

**Comment by reijo1337** [comment]
Блядь, ебаный ты шизоид, ты можешь нормально выражать свои мысли? Твой поток сознания читать просто не возможно. Возникает ощущение, что у тебя разорванное мышление или речевая бессвязность. Просто словесный шум какой-то. Прими таблетки и не забывай посещать психиатра, у которого наблюдаешься.
21 век, как ты такой неграмотный?
ВАШИНГТОН, ОКРУГ КОЛУМБИЯ МЭРАЙЯ КЕРИ ПОДЫХАЕТ ОТ ТОГО ЧТО ТИТЯНДРЫ СТАЛИ СЛИШКОМ БОЛЬШИМИ ЗАРАЖЕНИЕ КРОВИ, ПОДАГРА, ДИАБЕТ, ОТКАЗАЛИ ПОЧКИ, В КОНЦЕ КОНЦОВ ОТКАЗАЛО СЕРДЦЕ ГЛАВА КРИМИНАЛЬНОЙ ГРУППИРОВКИ 18-АЯ УЛИЦА И ДРУГ ДОНАЛЬДА ТРАМПА ХУАН КАРЛОС КАСТИЛЬЯ ПРИХОДИТ НА ПОХОРОНЫ ПЕВИЦЫ И ВСЕМ ГАЗЕТАМ И СМИ РАССКАЗЫВАЕТ, ЧТО РОДИТЕЛИ УМЕРШОЙ ОТРАБОТАЮТ ДОЛГ ДОЧЕРИ ПЕРЕД МАФИЕЙ ЗА КОКАИН НЕ ТАКАЯ УЖ ЧУДОВИЩНАЯ СУММА, ПОЛ МИЛЛИОНА БАКСОВ, РОДИТЕЛИ ПОГАСЯТ, ДРУЗЬЯ СОБЕРУТ
у тебя что, ИНТОКСИКАЦИЯ УКРАИНСКИМ МИРОМ?
Ладно, ты обсерился, я тебя понял. Можешь уходить.
Подите рот с мылом вымойте, товарищ.
Да ты ещё и неуравновешенный.Я понимаю что тебе приходится заниматься какой-то хернёй и возможно не об этом ты мечтал в жизни,но ты сам выбрал этот путь.Так что веди себя сдержанно и спокойно говори о том,как плохо высказывать своё недовольство как всё неплохо(могло быть и хуже) хочешь чтоб было как на Украине? и т.д. короче отрабатывай по инструкции,челядь
Другого я от тебя и не ждал, школьник максималист.
Пост-эталон малолетнего долбаёба.
Высрался ты конечно знатно. Словесный понос продемонстрировал. Всей лахтой эту пафосную хуитку сочиняли? А по сути то сказать тебе и нечего. Я считаю что пидорахи должны покинуть политач.
Ты понимаешь что ты шизоид?
Игорь, ты? Помнишь меня? Я твой одноклассник. Я узнал тебя по твоим шизоидным словам и высерам. А помнишь, как мы всем классом нассали тебе в кружку в третьем классе, на сладкоежке? Ты ещё выпил, облизнулся и попросил добавки. А потом тебя пришёл забирать твой отец, тот самый дворник, который на Вернадского изнасиловал собаку и получил условный срок за то, что украл плавленный сырок в магазине. Он зашёл в класс, все стали смеяться, а ты обосрался под себя от стыда, а потом сказал, что всю жизнь будешь ненавидеть дворником, но в 9м классе, когда ты пошёл на рейд, чтобы их отпиздить, то они пустили тебя по кругу, после чего тебе наложили на анус восемь швов. Как поживаешь, Игорян?
У тебя видать тоже кость широкая.
Танкисты пидарасы танкисты хуесосы танкисты долбоебы конченые
Мерзкий, тупой но сука смешной
И ты все такой же даун
тебе таблетки тоже не помогают?
Нахуй этого неадеквата.
Заебись. Тебе в любой теме пиздануть такое надо?
Пиздец у тебя чувство юмора, конечно...
Ты от дрочки похоже уже ослеп.
На цыпочках ходи в Москве, а то вдруг я услышу
Больше не имеешь права пиздеть
Даже Павло уже говорит, что ты конченый
В зеркало посмотри и повтори это снова и в слух
мне похуй, я твоё всё ебал, ты пидор, понял?
заткнись ты уже
твоя национальность гандон пиздабол
Бля, какая же ты девка ебаная, пиздец, ахахаха, ну и клоун
Потом опять будешь звонить и визжать в трубку
да зачем ты так часто это повторяешь, да еще и при всех. ты что, не уверен в себе (как обычно) и прикрываешь это своим гонором ?
Что ты мне ещё расскажешь, куколд
Ты гниль, у тебя проблемы с башкой, у меня не хватает зла на все, что ты высираешь, ты говно во всех смыслах, таких как ты тупо нужно запирать на острове и отбирать всю связь
Ну извини пожалуйста, но я не могу код из доки скопировать, тут как бы сети все же
обоссанный жид стучит кулачками от злости. пиздуй лекции писать по своему говну чтобы еще и от романова пропиздона не полкчить
Ты тут один пиздишь, я с тебя даже не спрашиваю больше потому что у тебя фляжка свистит
Какой же ты сука тупой
Ты шут, над тобой все смеются. Вот и все
Нудно гавно для пидорасов и просто хуета
Я тебя с одного уроню и ты обосрешься
Заткнись мне похуй на твои сообщения
Я не уважаю вообще нихуя и никого
Ты достал почему я должен с тобой обсуждать свою работу
Ты дождёшься точно, доведёшь меня
Не груби сука блядская
Спасибо хуесос что откликнулся
Да что ты тваю мать несёшь
Я подумал, и решил что ты гавно
Мы тут вроде обсудили что ты не имеешь права вякать про опенсорс
Да у меня побольше у тебя баллов по русскому было
Никто не считает тебя крутым
УУУ МЕНЯ В КАкую то хуйню взяли без диплома
Ты хаваешь и ничего не можешь сделать
Иди на хуй слышишь
Сейчас вы выглядите как будто у вас спермотоксикоз
Ахуеть, я как будто в детском садике сейчас
Твои слова — мусор
Ты заткнись с тобой вообще тут разговора никто не имел
Можешь даже не открывать рот, твоё мнение никого здесь не интересует
Зайду да пошлю тебя нахуй ущерба
Тупорылая ты тварь
Всегда знал, что эта поехавшая сука-хохлушка.
Твои понятия для меня вообще вне досягаемости
Не выдержал и начал как девочка писать гадости
Сразу видно человека который только что получил сеньора
Сиди жабу свою дрочи
Могу и куртку себе позволить, и кросы, и твою мать
Завяжи лямку ебаный рот
Скажи мне спасибо что я считаю тебя чмом
Лохозавр сельский
Это у вас Николо Пидорово насик кидают
Пиздобол, я родился здоровый как бык
Ты гандон дёрнись только с места я тебя уничтожу
Блять лёш ты такой уебок
Я о качетсве банка и не спорю, я говорю что ты гнильё
А ты по форме похож на пузыри пердежа под водой
Зачем? Да потому что пидорас и мудила
Я читаю тебя как дешевку
В очко себе вопрос задай, чмошник
Брёхин соси член прошманда
я ненавижу тебя алексей капустин
Не плачь уёбище
такой баян прям иди нахуй, тютя ебаная
Нюхай жопу
Твоя гражданская позиция это сидеть на очке
а к вечеру у тебя спина устала и жопа вспотела
за 50к проблемы со здоровьем, нет, спасибо
На самом деле, сглыпа это не бот, а я
давай объясняй, почему сливаешься с ринга, хоть раз веди себя как мужчина
У тебя фамилия хачарская
Это ты из лагеря детского такие слова принес?
Хотя общаешься как школьник-дебил, чего тебя интересно не взлюбили
Мне нужно только напоминать тебе почаще, что ты гондон ебаный, а по возможности я тебе еще и по ебучке щелкну
Я с тобой общаться не намерен, ты гниль опущенная
Чтобы по-настоящему посмеяться над несмешной шуткой, я вспоминаю твое лицо
Ты слишком плоско шутишь для своего веса
Ты являешься прямым доказательством того, что человек может жить без мозгов
Я так понимаю, что твой мозг идеально гладкий
Даже не знаю, что ты жрёшь по утрам. Но это точно не улучшает твой интеллект
Давай, ты просто уйдешь с миром. Уходишь? Хорошо... выпускайте собак
Сделаешь это ещё раз, запомнишь этот раз надолго
Ты такой умный. А я сильный - один раз бью в рыло, второй - по крышке гроба
Отлично выглядишь! Бухал вчера?
Не бойся, бить тебя я не буду. В наше время за избиение животных срок можно получить
Ладно, ты победил, у тебя хромосом больше
Унижать тебя слишком гнусно с моей стороны, тебя жизнь и так не хило потрепала
Тебе идёт мейк-ап а-ля дебил
Я тут договорился с работником кунсткамеры. Он сказал, что пустит тебя туда и при жизни
Я верю в силу человеческой личности, но ты, видно, не личность
Родился ты назло презервативу
Тебе не нужен презерватив, ведь ты и так гандон
Почему твой язык работает быстрее мозга?
Ты тупой или да?
Ты часом не баран по гороскопу?
Ты же хороший мальчик, зачем ты притворяешься дебилом?
Если бы у меня было такое лицо, как у тебя, я бы подал в суд на своих родителей
Тебя мама в детстве не обнимала?
Понарожают уродов
Захлопнись
Если ты выглядишь, как свинья, то это не значит, что нужно вести себя соответственно
Не доxуя ли ты дерзкий для своих габаритов?
У тебя рот как дверь от Жигулей, пока не ебанешь, хуй закроется
Как говорил мой дед: «Любишь кататься - катись нахуй»
Крылья за спиной растут или просто петухом становишься?
Я гляжу у тебя язык острый, а у меня жопа небритая
У тебя наверное член короткий, раз язык такой длинный
Можете, пожалуйста, говорить помедленнее? Я не успеваю класть хуй на все, что вы говорите
Ты как муравей, несешь всякую хуйню
Иди купи паяльник и запаяй себе ебальник
В тебе настолько много дерьма, что даже твои глаза карие
Ноги есть, тогда съебался отсюда
Уважаемый, не соблаговолите ли вы сгрести свою задницу в горсть и вынести ее нахуй
Почему у тебя такой выражение лица, словно всю ночь в жопу давал
Я думала, что ты рыцарь в доспехах, а оказался пиздабол в фольге
Заткните свои уста, уважаемый, всем похуй
Ты че объебался?
У тебя че, недотрах?
